#!/usr/bin/env python3

import argparse
import SRA_Tinder


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description=(
            "Find hot datasets in your area (of research)!"    
        ),        
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="\n".join([
            f'version: {SRA_Tinder.__version__}' 
        ])    
    )
    parser.set_defaults(func=lambda x: parser.print_help())

    # basic functions go here


    args = parser.parse_args()
    try:
        args.func(args)    
    except Exception as e:
        print(e)
        raise(e)



